-- return {
--   'brenoprata10/nvim-highlight-colors',
--   config = function()
--     require('nvim-highlight-colors').setup {
--       render = 'virtual',
--       virtual_symbol = '■',
--       virtual_symbol_prefix = '',
--       virtual_symbol_suffix = ' ',
--       virtual_symbol_position = 'inline',
--       custom_colors = {
--         { label = '%-%-theme%-primary%-color', color = '#0f1219' },
--         { label = '%-%-theme%-secondary%-color', color = '#5a5d64' },
--       },
--     }
--   end,
-- }
